export const projectsDB = [
  {
    address: "0x12E6F4388586A9133B9998DC5e4bA457D510059f",
    imageUrl: "https://source.unsplash.com/9_XdzTnrBWQ",
    location: "Monterrey, Mexico",
    title: "Lorem ipsum dolor sit",
    subTitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    minTokens: 50,
  },
  {
    address: "0x08B038Edb17c0edC1d767d2F5b0a081Ba61C6540",
    imageUrl: "https://source.unsplash.com/jU9VAZDGMzs",
    location: "Houston, United States",
    title: "Lorem ipsum dolor sit",
    subTitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    minTokens: 100,
  },
  {
    imageUrl: "https://source.unsplash.com/rqrTuepULx4",
    location: "Mexico City, Mexico",
    title: "Lorem ipsum dolor sit",
    subTitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    minTokens: 5,
  },
  {
    imageUrl: "https://source.unsplash.com/gHWj_kBebAc",
    location: "New York City, United States",
    title: "Lorem ipsum dolor sit",
    subTitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    minTokens: 100,
  },
  {
    imageUrl: "https://source.unsplash.com/1AnsoaUjXYQ",
    location: "Los Angeles, United States",
    title: "Lorem ipsum dolor sit",
    subTitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    minTokens: 45,
  },
  {
    imageUrl: "https://source.unsplash.com/LtG4vna9sJQ",
    location: "Guadalajara, Mexico",
    title: "Lorem ipsum dolor sit",
    subTitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    minTokens: 20,
  },
  {
    imageUrl: "https://source.unsplash.com/1kQwB7W0FLk",
    location: "Chicago, United States",
    title: "Lorem ipsum dolor sit",
    subTitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    minTokens: 30,
  },
  {
    imageUrl: "https://source.unsplash.com/gAwKd2LI9V0",
    location: "Monterrey, Mexico",
    title: "Lorem ipsum dolor sit",
    subTitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    minTokens: 10,
  },
  {
    imageUrl: "https://source.unsplash.com/EQ9EHig71TQ",
    location: "Dallas, United States",
    title: "Lorem ipsum dolor sit",
    subTitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    minTokens: 90,
  },
];
